
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '%I\x16^\x84\x13\xb2\xfb~\x06u+\xb4\x15\xa8\xb9'

_lr_action_items = {'SEMI':([4,9,10,13,],[8,-4,-5,-6,]),'BROADCAST':([2,],[6,]),'URGENT':([0,1,3,8,],[-2,2,-1,-3,]),'COMMA':([9,10,13,],[12,-5,-6,]),'IDENTIFIER':([5,7,11,12,],[10,-7,-8,13,]),'CHANNEL':([2,6,],[7,11,]),'$end':([0,1,3,8,],[-2,0,-1,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'VariableDecl':([1,],[4,]),'VariableList':([5,],[9,]),'Declarations':([0,],[1,]),'Type':([1,],[5,]),'Declaration':([1,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('Declarations',2,'p_Declarations','/home/andreas/Dokumenter/uni/ulp/parser.py',37),
  ('Declarations',0,'p_Declarations','/home/andreas/Dokumenter/uni/ulp/parser.py',38),
  ('Declaration',2,'p_Declaration','/home/andreas/Dokumenter/uni/ulp/parser.py',49),
  ('VariableDecl',2,'p_VariableDecl','/home/andreas/Dokumenter/uni/ulp/parser.py',55),
  ('VariableList',1,'p_VariableList','/home/andreas/Dokumenter/uni/ulp/parser.py',67),
  ('VariableList',3,'p_VariableList','/home/andreas/Dokumenter/uni/ulp/parser.py',68),
  ('Type',2,'p_Type','/home/andreas/Dokumenter/uni/ulp/parser.py',73),
  ('Type',3,'p_Type','/home/andreas/Dokumenter/uni/ulp/parser.py',74),
  ('TYPE',1,'p_Type','/home/andreas/Dokumenter/uni/ulp/parser.py',75),
  ('TYPE',1,'p_Type','/home/andreas/Dokumenter/uni/ulp/parser.py',76),
  ('TYPE',2,'p_Type','/home/andreas/Dokumenter/uni/ulp/parser.py',77),
  ('TYPE',2,'p_Type','/home/andreas/Dokumenter/uni/ulp/parser.py',78),
  ('TYPE',1,'p_Type','/home/andreas/Dokumenter/uni/ulp/parser.py',79),
  ('TYPE',1,'p_Type','/home/andreas/Dokumenter/uni/ulp/parser.py',80),
]
